Repository vmware/powershell-module-for-vmware-cloud-foundation-certificate-management, pull requests merged in 2023-07, with the labels that each got.

#47 docs: fix-up docs
  VMware.CloudFoundation.CertificateManagement.psm1
  docs/documentation/functions/Confirm-CAInvCenterServer.md
  docs/documentation/functions/Confirm-EsxiCertificateInstalled.md
  docs/documentation/functions/Get-EsxiCertificateMode.md
  docs/documentation/functions/Get-EsxiCertificateThumbprint.md
  docs/documentation/functions/Get-EsxiLockdownMode.md
  docs/documentation/functions/Get-vCenterCertificateThumbprint.md
  docs/documentation/functions/Get-vSANHealthSummary.md
  docs/documentation/functions/Install-EsxiCertificate.md
  docs/documentation/functions/Request-EsxiCsr.md
  docs/documentation/functions/Restart-EsxiHost.md
  docs/documentation/functions/Set-EsxiCertificateMode.md
  docs/documentation/functions/Set-EsxiLockdownMode.md
  docs/documentation/functions/Test-EsxiCertMgmtChecks.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, cla-not-required, needs-review

#45 feat: enhance test connection functions
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: documentation, cla-not-required

#49 chore: release preparation
  .gitignore
  CHANGELOG.md
  Makefile
  docs/index.md
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, chore, cla-not-required

#50 docs: update docs
  docs/index.md
Labels: documentation, cla-not-required

#51 chore(gh): add to project
  .github/workflows/project.yml
Labels: chore, cla-not-required, github-actions
