Repository vmware/powershell-module-for-vmware-cloud-foundation-certificate-management, pull requests merged in 2023-10, with the labels that each got.

#78 fix: update `Get-vSANHealthSummary` to report correct status
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: cla-not-required

#76 chore(ci): update actions
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: chore, cla-not-required

#79 chore(ci): update tests
  .github/workflows/tests.yml
Labels: chore, cla-not-required

#81 chore: release preparation
  CHANGELOG.md
  Makefile
  VMware.CloudFoundation.CertificateManagement.psd1
  docs/index.md
  docs/requirements.txt
  docs/snippets/install-module.ps1
Labels: chore, cla-not-required

#82 docs: update supported versions
  docs/index.md
Labels: cla-not-required

#83 docs: update support
  README.md
  docs/community/index.md
  docs/community/support.md
Labels: documentation, cla-not-required
