Repository vmware/powershell-module-for-vmware-cloud-foundation-certificate-management, pull requests merged in 2023-05, with the labels that each got.

#14 feat: add esxi certificate management cmdlets
  README.md
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: documentation, cla-not-required, under-review

#15 chore: add parameter descriptions
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: chore, cla-not-required

#16 chore: update cmdlet details
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: cla-not-required, needs-review

#17 docs: add cmdlet documentation
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
  docs/functions/Confirm-CAInvCenterServer.md
  docs/functions/Confirm-ESXiCertificateInstalled.md
  docs/functions/Get-ESXiLockdownMode.md
  docs/functions/Get-EsxiCertificateThumbprint.md
  docs/functions/Get-vCenterCertManagementMode.md
  docs/functions/Get-vCenterCertificateThumbprint.md
  docs/functions/Get-vSANHealthSummary.md
  docs/functions/Install-EsxiCertificate.md
  docs/functions/Request-EsxiCsr.md
  docs/functions/Restart-ESXiHost.md
  docs/functions/Set-ESXiLockdownMode.md
  docs/functions/Set-vCenterCertManagementMode.md
Labels: documentation, cla-not-required, needs-review

#20 docs: update `README.md`
  README.md
Labels: documentation, cla-not-required, needs-review

#23 docs: uodate README.md
  README.md
Labels: documentation, cla-not-required, needs-review

#24 chore: release updates
  CHANGELOG.md
  README.md
  VMware.CloudFoundation.CertificateManagement.psd1
Labels: chore

#25 docs: update README.md
  README.md
Labels: documentation, cla-not-required, needs-review
