Repository vmware/powershell-module-for-vmware-cloud-foundation-certificate-management, pull requests merged in 2024-01, with the labels that each got.

#103 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  README.md
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
Labels: documentation, chore, cla-not-required, needs-review

#104 docs: documentation updates
  docs/community/index.md
  docs/index.md
  docs/requirements.txt
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
  mkdocs.yml
Labels: documentation, cla-not-required

#105 chore(deps): support pwsh 7.2 and later
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
  docs/index.md
  docs/install.md
Labels: documentation, breaking-change, chore, cla-not-required, needs-review

#101 feat: add migration mode option to `Install-EsxiCertificate`
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
  VMware.CloudFoundation.CertificateManagement.psm1
  docs/documentation/functions/Get-EsxiHostVsanMaintenanceModePrecheck.md
  docs/documentation/functions/Install-VCFCertificate.md
Labels: documentation, cla-not-required, needs-review

#106 chore: set next release
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
Labels: documentation, chore, cla-not-required, needs-review

#107 chore(deps): bump powervcf from 2.4.0 to 2.4.1
  CHANGELOG.md
  VMware.CloudFoundation.CertificateManagement.psd1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, chore, cla-not-required, dependencies, needs-review

#108 chore: release v1.5.1
  CHANGELOG.md
Labels: documentation, chore, cla-not-required
